### ISSUE TITLE
Summary of the project

### ISSUE THREAD

**Issue by miewan** [dateiexplorer/autonomously-driving-vehicle#1]
Hi, can you tell me the summary of this project. I mean what it did? Is this for perception and prediction?

**Comment by dateiexplorer** [comment]
Hey miewan,

this repo ist the result of an university project and it just simulates an vehicle.
The goal of this project was to implement (and learn) various design patterns and not to implement a solution for a "real" autonomously driving vehicle. So far, it doesn't include any code that makes the simulated vehicle autonomous. The repo name was given by our professor.

But thanks, i would like to add this in a README to clarify that.

**Comment by miewan** [comment]
Based on the code it can be assumed that this project use data from camera
and lidar right?

**Comment by dateiexplorer** [comment]
Yes and now, the camera and the lidar are just simulated components too. Currently they don't generate any data or offer any functionality you would expect from this components.
As I said, this is just a simple simulation and the focus of the project is at the programming side and the implementation of various design patterns not at the implementation of a functional driving vehicle.

**Comment by miewan** [comment]
Ok, thanks for the clarification. Do you have any architecture before
implementing the design pattern it?

**Comment by dateiexplorer** [comment]
No, the intention of this project was to design it with specific design patterns (the project doesn't exist before), they were given by our professor. To be honest, I would change some things to improve the architecture of the project, because there were mixed up too many design patterns together. But our professor wants, that we design it this way.

**Comment by miewan** [comment]
Thank you for the clarification.
